spring:
  application:
    name: gateway-service


  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: insper
              uri: http://www.insper.edu.br ## hostname da maquina
              predicates:
                - Path=/insper/**

            - id: accounts
              uri: http://account:8080 ## hostname da maquina
              predicates:
                - Path=/accounts/**

            - id: auth
              uri: http://auth:8080 ## hostname da maquina
              predicates:
                - Path=/auth/**

          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: ${CORS_ALLOWED_ORIGINS:*}
                allowedHeaders: "*"
                allowedMethods: "*"
                allowedCredentials: ${CORS_ALLOWED_CREDENTIALS:true}
                
